### ISSUE TITLE
在n1里面部署docker出错

### ISSUE THREAD

**Issue by jmullen2** [srcrs/unicom-task#43]
启动docker出错，提示
Containers: start 7e71f54f842cfbea7f5af878a6a69f25bf19bf5bc0f912cb97a807aac3b39daf...code:304 Not Modified
是什么情况，

**Comment by jmullen2** [comment]
standard_init_linux.go:211: exec user process caused "exec format error，是不是镜像不兼容arm的cpu

**Comment by edison0354** [comment]
R2S也一样……

**Comment by gold2wave** [comment]
同n1部署失败

**Comment by edison0354** [comment]
换个镜像：

https://github.com/srcrs/unicom-task/issues/6#issuecomment-886178124

虽然但是，我还是在报错，怀疑是config写错了？

**Comment by gold2wave** [comment]
> 换个镜像，R2S亲测可用，可以进去容器手动跑一遍试试先～
> 
> [#6 (comment)](https://github.com/srcrs/unicom-task/issues/6#issuecomment-886178124)

请问可以具体说说怎么操作吗?谢谢

**Comment by gold2wave** [comment]
> 换个镜像，R2S亲测可用，可以进去容器手动跑一遍试试先～
> 
> [#6 (comment)](https://github.com/srcrs/unicom-task/issues/6#issuecomment-886178124)

Error response from daemon: Container cf3f618f79baa1cd47ee48c7f112203e6fa56475bea60c8221fc029c52690c63 is restarting, wait until the container is running
运行出错

**Comment by edison0354** [comment]
> > 换个镜像，R2S亲测可用，可以进去容器手动跑一遍试试先～
> > [#6 (comment)](https://github.com/srcrs/unicom-task/issues/6#issuecomment-886178124)
> 
> Error response from daemon: Container cf3f618f79baa1cd47ee48c7f112203e6fa56475bea60c8221fc029c52690c63 is restarting, wait until the container is running
> 运行出错

你用啥跑的？就把拉取镜像名字换一下就好了啊。不行的话把旧的容器删干净重来试试？

docker-compose的话改成这样

```
version: "3.1"

services:
  unicom-task:
    image: dellear/unicom-task:latest
    working_dir: /root
    network_mode: "host"
    restart: always
    command:
      - /bin/bash
      - -c
      - |
         service cron start
         sleep infinity
    volumes:
      - $PWD/config:/config
```
